# This is a basic workflow to help you get started with Actions

name: CRAWL

on:
  push:
    branches: [ master ]
  # schedule: 
  #   - cron: "0 0,9 * * *" # 09:00 GMT+09:00 / 18:00 GMT+09:00
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17.x]
      
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
  
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npx tsc
      - run: ls -al
      - run: npm run crawl